version: "2"
services:
  app:
    build: .
    image: keboola/ex-db-mssql-cdata
    command: composer ci
    tty: true
    stdin_open: true
    env_file:
      - ssh-keys.env
    environment:
      MSSQL_RTK_LICENSE: 52554445555A303830313139333057454254523141310000000000000000000000000000000000004546324A4452313200004D353038374E57475A5A52440000
      MSSQL_DB_HOST: mssql
      MSSQL_DB_PORT: 1433
      MSSQL_DB_USER: sa
      MSSQL_DB_PASSWORD: "yourStrong(!)Password"
      MSSQL_DB_DATABASE: test
    links:
      - sshproxy
      - mssql

  dev: &dev-config
    image: keboola/ex-db-mssql-cdata-dev
    build:
      context: .
    volumes:
      - .:/code
    command: composer ci
    tty: true
    stdin_open: true
    env_file:
      - ssh-keys.env
    environment:
      MSSQL_RTK_LICENSE: 52554445555A303830313139333057454254523141310000000000000000000000000000000000004546324A4452313200004D353038374E57475A5A52440000
      MSSQL_DB_HOST: mssql
      MSSQL_DB_PORT: 1433
      MSSQL_DB_USER: sa
      MSSQL_DB_PASSWORD: "yourStrong(!)Password"
      MSSQL_DB_DATABASE: test
    links:
      - sshproxy
      - mssql

  dev-xdebug:
    <<: *dev-config
    image: keboola/ex-db-mssql-cdata-dev-xdebug
    build: docker/xdebug

  mssql:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"

  sshproxy:
    build: ./tests/env/sshproxy
    volumes:
        - ./tests/env/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"
    links:
      - mssql
