version: "2"
services:
  app:
    build:
      context: .
      args:
        RTK_LICENSE_BUILD_ARG: $RTK_LICENSE
    image: keboola/ex-db-mssql-cdata
    command: composer ci
    tty: true
    stdin_open: true
    env_file:
      - ssh-keys.env
    environment:
      MSSQL_DB_HOST: mssql
      MSSQL_DB_PORT: 1433
      MSSQL_DB_USER: sa
      MSSQL_DB_PASSWORD: "yourStrong(!)Password"
      MSSQL_DB_DATABASE: test

  dev: &dev-config
    image: keboola/ex-db-mssql-cdata-dev
    build:
      context: .
      args:
        RTK_LICENSE_BUILD_ARG: $RTK_LICENSE
    volumes:
      - .:/code
    command: composer ci
    tty: true
    stdin_open: true
    env_file:
      - ssh-keys.env
    environment:
      MSSQL_DB_HOST: mssql
      MSSQL_DB_PORT: 1433
      MSSQL_DB_USER: sa
      MSSQL_DB_PASSWORD: "yourStrong(!)Password"
      MSSQL_DB_DATABASE: test
